name: TestCafe Git Commit Workflow
on: [push]

jobs:
  build:
    name: TestCafe Git Job
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run testcafe from specified commit
        uses: AlexKamaev/testcafe-action@v0.0.1-alpha.1
        with:
          branch: master
          commit: ad43ce086573d9da15a813690e992ed560246f59
          testCafeArguments: "chrome tests"
